
title: My Port 
email: tangrianekolisnichenco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Bem vindo ao site de teste
baseurl: "" # the subpath of your site, e.g. /blog
url: "tangriane.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tangriane_k
github_username:  tangriane

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
